import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { SkillProposalService } from "../SkillProposalService";

const dirs: string[] = [];
afterEach(() => {
  for (const dir of dirs.splice(0)) fs.rmSync(dir, { recursive: true, force: true });
});

function workspace() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "skill-proposals-"));
  dirs.push(dir);
  return dir;
}

function writeLegacy(root: string, id: string, status: "pending" | "approved") {
  const dir = path.join(root, ".cowork", "skills", "proposals");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(
    path.join(dir, `${id}.json`),
    JSON.stringify({
      id,
      version: 1,
      status,
      problemStatement: 'Recurring task pattern detected (reinforced 3 times): "Deploy"',
      evidence: ["Pattern reinforced 3 times across different tasks"],
      requiredTools: [],
      riskNote: "Auto-generated from PlaybookSkillPromoter based on repeated successful patterns.",
      draftSkill: {
        id: "auto_deploy",
        name: "Deploy",
        description: "d",
        prompt: "p",
        category: "auto-promoted",
      },
      signature: "s",
      createdAt: 1,
      updatedAt: 1,
    }),
  );
}

describe("SkillProposalService evidence status", () => {
  it("gates pending legacy auto-proposals and flags approved ones without touching them", async () => {
    const root = workspace();
    writeLegacy(root, "sp_legacy_pending", "pending");
    writeLegacy(root, "sp_legacy_approved", "approved");
    const service = new SkillProposalService(root);

    const pending = await service.get("sp_legacy_pending");
    expect(pending?.evidenceStatus).toBe("unverified");
    expect(await service.approve("sp_legacy_pending", "auto_deploy")).toBeNull();
    expect((await service.get("sp_legacy_pending"))?.status).toBe("pending");

    const approved = await service.get("sp_legacy_approved");
    expect(approved).toMatchObject({ status: "approved", evidenceStatus: "unverified" });
  });

  it("evidence-backed and authored proposals remain approvable", async () => {
    const service = new SkillProposalService(workspace());
    const backed = await service.create({
      problemStatement: "Recurring task pattern with 3 observed successful executions",
      riskNote: "Auto-generated by PlaybookSkillPromoter from the Playbook evidence ledger.",
      provenance: {
        source: "playbook_evidence",
        evidenceIds: ["e1", "e2", "e3"],
        executionCount: 3,
      },
      draftSkill: {
        id: "auto_run_tests",
        name: "Run tests",
        description: "d",
        prompt: "p",
        category: "auto-promoted",
      },
    });
    expect(backed.proposal?.evidenceStatus).toBe("evidence_backed");
    expect(await service.approve(backed.proposal!.id, "auto_run_tests")).toMatchObject({
      status: "approved",
    });

    const authored = await service.create({
      problemStatement: "Manual proposal",
      draftSkill: { id: "manual_skill", name: "Manual", description: "d", prompt: "p" },
    });
    expect(authored.proposal?.evidenceStatus).toBe("not_applicable");
  });
});
