import snapshot from "./model-metadata.json";

/**
 * Model prices and limits from the bundled models.dev snapshot
 * (src/shared/model-metadata.json, regenerated by `npm run models:sync`).
 * Prices are USD per 1M tokens.
 */
export interface ModelMetadataEntry {
  provider: string;
  input?: number;
  output?: number;
  cacheRead?: number;
  cacheWrite?: number;
  /** Rates that apply to the whole request once input exceeds `threshold` tokens. */
  longContext?: {
    threshold: number;
    input: number;
    output: number;
    cacheRead?: number;
    cacheWrite?: number;
  };
  context?: number;
  maxOutput?: number;
}

const BUNDLED = (snapshot as { models: Record<string, ModelMetadataEntry> }).models;

export const MODEL_METADATA_GENERATED_AT = (snapshot as { generatedAt: string }).generatedAt;

// Runtime layers, checked before the bundled snapshot (main process only):
//  - live: data a provider reported while CoWork listed its models (e.g. OpenRouter);
//  - refreshed: a newer models.dev catalogue from the opt-in daily refresh.
const LIVE = new Map<string, ModelMetadataEntry>();
let REFRESHED: Record<string, ModelMetadataEntry> | null = null;

/** Record provider-reported prices/limits. Later reports for the same id replace earlier ones. */
export function registerLiveModelMetadata(entries: Record<string, ModelMetadataEntry>): void {
  for (const [id, entry] of Object.entries(entries)) {
    const key = id.trim().toLowerCase();
    if (key) LIVE.set(key, entry);
  }
}

/** Replace the refreshed catalogue layer; pass null to fall back to the bundled snapshot. */
export function setRefreshedModelMetadata(models: Record<string, ModelMetadataEntry> | null): void {
  REFRESHED = models;
}

/** Test helper: drop runtime layers so lookups use the bundled snapshot only. */
export function resetRuntimeModelMetadata(): void {
  LIVE.clear();
  REFRESHED = null;
}

// Bedrock cross-region inference prefixes, e.g. "us.anthropic.claude-opus-4-6-v1".
const BEDROCK_REGION_PREFIX = /^(?:us|eu|apac|au|jp|ca|global|us-gov)\./;
// Route variants such as OpenRouter's ":free" / ":thinking" (not Bedrock's "-v1:0").
const ROUTE_VARIANT_SUFFIX = /:(?:[a-z][a-z-]*)$/;
const DATE_SUFFIX = /-(?:\d{8}|\d{4}-\d{2}-\d{2})$/;
const CATALOG_CLAUDE_KEY = /^(?:opus|sonnet|haiku|fable)-\d/;

/**
 * Candidate ids for one model, most specific first. Matching is exact on each
 * candidate — no substring matching, so "gpt-4.1" can never pick up "gpt-4".
 */
export function modelIdCandidates(modelId: string): string[] {
  const out: string[] = [];
  const add = (value: string | undefined) => {
    const v = value?.trim().toLowerCase();
    if (v && !out.includes(v)) out.push(v);
  };

  const raw = String(modelId || "")
    .trim()
    .toLowerCase();
  if (!raw) return out;
  add(raw);

  // Vertex-style "claude-opus-4-5@20251101" and route variants.
  const base = raw.split("@", 1)[0].replace(ROUTE_VARIANT_SUFFIX, "");
  add(base);

  // Route prefixes: "openai-codex/gpt-6-astra", "z-ai/glm-5", "anthropic/claude-opus-4.6".
  const unprefixed = base.includes("/") ? base.slice(base.lastIndexOf("/") + 1) : base;
  add(unprefixed);

  // Bedrock: "us.anthropic.claude-opus-4-6-v1" -> "anthropic.claude-opus-4-6-v1" -> "claude-opus-4-6".
  const regionless = unprefixed.replace(BEDROCK_REGION_PREFIX, "");
  add(regionless);
  // Bedrock ids saved without their version suffix ("anthropic.claude-opus-4-6") should
  // still get Bedrock's price, not the vendor's direct price.
  if (/^[a-z]+\.[a-z]/.test(regionless) && !/-v\d+(?::\d+)?$/.test(regionless)) {
    add(`${regionless}-v1`);
    add(`${regionless}-v1:0`);
  }
  const vendorless = regionless
    .replace(/^(?:anthropic|meta|amazon|mistral|cohere|deepseek|openai|qwen)\./, "")
    .replace(/-v\d+(?::\d+)?$/, "");
  add(vendorless);

  // CoWork catalog keys: "opus-4-6" -> "claude-opus-4-6".
  if (CATALOG_CLAUDE_KEY.test(vendorless)) add(`claude-${vendorless}`);

  // Snapshot the list: variants are derived from the ids above, not from each other.
  for (const candidate of out.slice()) {
    // Version separators differ by provider: "claude-opus-4.6" vs "claude-opus-4-6".
    add(candidate.replace(/(\d)\.(\d)/g, "$1-$2"));
    add(candidate.replace(/(\d)-(\d)(?!\d)/g, "$1.$2"));
    add(candidate.replace(DATE_SUFFIX, ""));
    add(candidate.replace(/-latest$/, ""));
    // Dated previews priced like their GA model: "gemini-2.5-pro-preview-05-06".
    add(candidate.replace(/-preview-\d{2}-\d{2}$/, ""));
  }
  return out;
}

/** Exact lookup of one already-normalized candidate id (see modelIdCandidates). */
export function lookupModelMetadata(candidateId: string): ModelMetadataEntry | null {
  const live = LIVE.get(candidateId);
  const fallback = REFRESHED?.[candidateId] ?? BUNDLED[candidateId] ?? null;
  if (!live) return fallback;
  // Providers may report a price without a limit (or vice versa); fill gaps from the catalogue.
  return fallback ? { ...fallback, ...live } : live;
}

export function resolveModelMetadata(modelId: string): ModelMetadataEntry | null {
  for (const candidate of modelIdCandidates(modelId)) {
    const entry = lookupModelMetadata(candidate);
    if (entry) return entry;
  }
  return null;
}

export function getModelContextWindow(modelId: string): number | null {
  return resolveModelMetadata(modelId)?.context ?? null;
}
