import {
  Activity,
  Apple,
  Award,
  Baby,
  Bed,
  Bell,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Cake,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  ChefHat,
  CircleCheck,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crown,
  DollarSign,
  Droplet,
  Dumbbell,
  Euro,
  Film,
  Flag,
  Flame,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  HeartPulse,
  Hotel,
  Hourglass,
  House,
  Info,
  Key,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  Moon,
  Mountain,
  Music,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PoundSterling,
  Receipt,
  Recycle,
  Repeat,
  Rocket,
  Ruler,
  Scale,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  TrainFront,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Umbrella,
  User,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import {
  isAnswerSurfaceIcon,
  type AnswerSurfaceIconName,
} from "../../../shared/answer-surfaces/icons";

const ICONS: Record<AnswerSurfaceIconName, LucideIcon> = {
  activity: Activity,
  alert: TriangleAlert,
  apple: Apple,
  award: Award,
  baby: Baby,
  bed: Bed,
  bell: Bell,
  bike: Bike,
  book: BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  cake: Cake,
  calculator: Calculator,
  calendar: CalendarDays,
  camera: Camera,
  car: Car,
  "chart-bar": ChartColumn,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  check: Check,
  "check-circle": CircleCheck,
  "chef-hat": ChefHat,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  "credit-card": CreditCard,
  crown: Crown,
  dollar: DollarSign,
  droplet: Droplet,
  dumbbell: Dumbbell,
  euro: Euro,
  film: Film,
  flag: Flag,
  flame: Flame,
  footprints: Footprints,
  gamepad: Gamepad2,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "heart-pulse": HeartPulse,
  home: House,
  hotel: Hotel,
  hourglass: Hourglass,
  info: Info,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  medal: Medal,
  message: MessageCircle,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  package: Package,
  palette: Palette,
  party: PartyPopper,
  paw: PawPrint,
  percent: Percent,
  phone: Phone,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  pound: PoundSterling,
  rain: CloudRain,
  receipt: Receipt,
  recycle: Recycle,
  repeat: Repeat,
  rocket: Rocket,
  ruler: Ruler,
  scale: Scale,
  shield: Shield,
  ship: Ship,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  store: Store,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  target: Target,
  tent: Tent,
  thermometer: Thermometer,
  ticket: Ticket,
  timer: Timer,
  train: TrainFront,
  tree: TreePine,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  waves: Waves,
  wind: Wind,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
};

/** A named icon from the surface icon set, or an emoji the model chose instead. */
export function SurfaceIcon({ name, className }: { name?: string; className?: string }) {
  if (!name) return null;
  if (isAnswerSurfaceIcon(name)) {
    const Icon = ICONS[name];
    return <Icon className={className} aria-hidden="true" strokeWidth={2} />;
  }
  return (
    <span className={`${className ?? ""} as-icon-emoji`.trim()} aria-hidden="true">
      {name}
    </span>
  );
}
