import type Database from "better-sqlite3";
import type { UnitCatalog } from "../database/statements/statement-catalog";
import { clockedStoreUnit } from "../database/statements/store-units";
import { PactStore } from "./pact-sql";

const make = (db: Database.Database, now: () => number) => new PactStore(db, now);

/** PACT persistence units (plan §8), in the services domain; clocked so tests inject time. */
export const PACT_UNITS = {
  pact_upsertProvider: clockedStoreUnit(make, "upsertProvider", { readonly: false }),
  pact_getProvider: clockedStoreUnit(make, "getProvider", { readonly: true }),
  pact_getProviderByOrigin: clockedStoreUnit(make, "getProviderByOrigin", { readonly: true }),
  pact_listProviders: clockedStoreUnit(make, "listProviders", { readonly: true }),
  pact_upsertBusiness: clockedStoreUnit(make, "upsertBusiness", { readonly: false }),
  pact_getBusiness: clockedStoreUnit(make, "getBusiness", { readonly: true }),
  pact_getBusinessByCardUrl: clockedStoreUnit(make, "getBusinessByCardUrl", { readonly: true }),
  pact_listBusinesses: clockedStoreUnit(make, "listBusinesses", { readonly: true }),
  pact_ensureSubjectBinding: clockedStoreUnit(make, "ensureSubjectBinding", { readonly: false }),
  pact_getSubjectBinding: clockedStoreUnit(make, "getSubjectBinding", { readonly: true }),
  pact_insertGrant: clockedStoreUnit(make, "insertGrant", { readonly: false }),
  pact_getGrant: clockedStoreUnit(make, "getGrant", { readonly: true }),
  pact_listGrants: clockedStoreUnit(make, "listGrants", { readonly: true }),
  pact_updateGrant: clockedStoreUnit(make, "updateGrant", { readonly: false }),
  pact_createConversation: clockedStoreUnit(make, "createConversation", { readonly: false }),
  pact_getConversation: clockedStoreUnit(make, "getConversation", { readonly: true }),
  pact_findUsableConversation: clockedStoreUnit(make, "findUsableConversation", {
    readonly: true,
  }),
  pact_updateConversation: clockedStoreUnit(make, "updateConversation", { readonly: false }),
  pact_listConversations: clockedStoreUnit(make, "listConversations", { readonly: true }),
  pact_prepareMessage: clockedStoreUnit(make, "prepareMessage", { readonly: false }),
  pact_getMessage: clockedStoreUnit(make, "getMessage", { readonly: true }),
  pact_listMessages: clockedStoreUnit(make, "listMessages", { readonly: true }),
  pact_findOperation: clockedStoreUnit(make, "findOperation", { readonly: true }),
  pact_beginAttempt: clockedStoreUnit(make, "beginAttempt", { readonly: false }),
  pact_beginReconcile: clockedStoreUnit(make, "beginReconcile", { readonly: false }),
  pact_renewAttemptLease: clockedStoreUnit(make, "renewAttemptLease", { readonly: false }),
  pact_finishAttempt: clockedStoreUnit(make, "finishAttempt", { readonly: false }),
  pact_updateMessage: clockedStoreUnit(make, "updateMessage", { readonly: false }),
  pact_markAbandonedAttempts: clockedStoreUnit(make, "markAbandonedAttempts", { readonly: false }),
  pact_insertAuthorization: clockedStoreUnit(make, "insertAuthorization", { readonly: false }),
  pact_getAuthorization: clockedStoreUnit(make, "getAuthorization", { readonly: true }),
  pact_getAuthorizationByInputRequest: clockedStoreUnit(make, "getAuthorizationByInputRequest", {
    readonly: true,
  }),
  pact_listAuthorizations: clockedStoreUnit(make, "listAuthorizations", { readonly: true }),
  pact_acquireAuthorizationLease: clockedStoreUnit(make, "acquireAuthorizationLease", {
    readonly: false,
  }),
  pact_linkAuthorizationInput: clockedStoreUnit(make, "linkAuthorizationInput", {
    readonly: false,
  }),
  pact_settleAuthorization: clockedStoreUnit(make, "settleAuthorization", { readonly: false }),
  pact_insertReceipt: clockedStoreUnit(make, "insertReceipt", { readonly: false }),
  pact_getReceipt: clockedStoreUnit(make, "getReceipt", { readonly: true }),
  pact_listReceipts: clockedStoreUnit(make, "listReceipts", { readonly: true }),
  pact_counts: clockedStoreUnit(make, "counts", { readonly: true }),
  pact_metrics: clockedStoreUnit(make, "metrics", { readonly: true }),
} satisfies UnitCatalog;

export const PACT_STORE_METHODS = [
  "upsertProvider",
  "getProvider",
  "getProviderByOrigin",
  "listProviders",
  "upsertBusiness",
  "getBusiness",
  "getBusinessByCardUrl",
  "listBusinesses",
  "ensureSubjectBinding",
  "getSubjectBinding",
  "insertGrant",
  "getGrant",
  "listGrants",
  "updateGrant",
  "createConversation",
  "getConversation",
  "findUsableConversation",
  "updateConversation",
  "listConversations",
  "prepareMessage",
  "getMessage",
  "listMessages",
  "findOperation",
  "beginAttempt",
  "beginReconcile",
  "renewAttemptLease",
  "finishAttempt",
  "updateMessage",
  "markAbandonedAttempts",
  "insertAuthorization",
  "getAuthorization",
  "getAuthorizationByInputRequest",
  "listAuthorizations",
  "acquireAuthorizationLease",
  "linkAuthorizationInput",
  "settleAuthorization",
  "insertReceipt",
  "getReceipt",
  "listReceipts",
  "counts",
  "metrics",
] as const;
